steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
#  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
#    args:
#      - '-Dsonar.host.url=https://sonarcloud.io'
#      - '-Dsonar.login=d292f9bc72892e8521952851c5163589a1c23957'
#      - '-Dsonar.projectKey=gcp-cs'
#      - '-Dsonar.organization=tmaskibail'
#      - '-Dsonar.sources=.'
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer-service:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-service:$COMMIT_SHA']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s/customer-service-dev.yaml
      - --image=gcr.io/$PROJECT_ID/customer-service:$COMMIT_SHA
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
images: ['gcr.io/$PROJECT_ID/customer-service:$COMMIT_SHA']
#tags: ['cloud-builders-community']
