apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: customer-service
build:
  artifacts:
  - image: gcr.io/dev-env-274010/customer-service
deploy:
  kubectl:
    manifests:
    - k8s/base-admin-resources-dev.yaml
    - k8s/customer-service-dev.yaml
