apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: customer-service
build:
  artifacts:
  - image: urthilak/customer-service
deploy:
  kubectl:
    manifests:
    - k8s/customer-service-dev.yaml
