apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customer-service
  name: customer-service
spec:
  ports:
  - name: customer-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer-service
  type: ClusterIP
status:
  loadBalancer: {}
