apiVersion: v1
kind: Namespace
metadata:
  name: dev
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
data:
  spring.user.name: ZGVtbw==
  spring.user.password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: customer-service-security
  namespace: dev
type: Opaque
---
apiVersion: v1
data:
  LOG_DIR: /app/logs
kind: ConfigMap
metadata:
  name: customer-service-configmap
  namespace: dev